spring.application.name=resume
server.port=8888
spring.datasource.url=jdbc:postgresql://localhost:4999/db
spring.datasource.username=user
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.database-platform =org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=glucharik2@gmail.com
spring.mail.password=duwr efog taxe gvnz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/

# Logging
logging.file.name=logs/application.log
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

#security
spring.security.user.name=admin
spring.security.user.password=12345

spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=resume
spring.security.oauth2.client.registration.keycloak.client-name=resume
spring.security.oauth2.client.registration.keycloak.client-secret=w9E3StaKRRxAKgeqqukYhCVyJEMC4KUA
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid profile email
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/resume
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/resume/protocol/openid-connect/certs