spring.application.name=resume
server.port=8888
spring.datasource.url=jdbc:postgresql://localhost:4999/db
spring.datasource.username=user
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.database-platform =org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=glucharik2@gmail.com
spring.mail.password=duwr efog taxe gvnz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/

# Logging
logging.file.name=logs/application.log
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

#security
spring.security.user.name=admin
spring.security.user.password=12345