### Получить токен администратора Keycloak с scope=openid
POST http://localhost:8081/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin-cli&grant_type=password&username=admin&password=12345&scope=openid

> {%
client.global.set("keycloak_admin_token_with_openid", response.body.access_token);
client.global.set("keycloak_refresh_token", response.body.refresh_token);
%}

### Получение реалмов
GET http://localhost:8081/admin/realms
Authorization: Bearer {{keycloak_admin_token_with_openid}}

### Создать пользователя в Keycloak (требует админские права)
POST http://localhost:8081/admin/realms/master/users
Content-Type: application/json
Authorization: Bearer {{keycloak_admin_token_with_openid}}

{
  "username": "user2",
  "email": "user12221@example.com",
  "firstName": "Имя144",
  "lastName": "Фамилия",
  "enabled": true,
  "credentials": [
    {
      "type": "password",
      "value": "пароль123",
      "temporary": false
    }
  ]
}

### Поиск пользователя по username (замените 'testuser' на нужное)
GET http://localhost:8081/admin/realms/master/users?username=user2
Authorization: Bearer {{keycloak_admin_token_with_openid}}
Content-Type: application/json